### ISSUE TITLE
uapp 未来开发计划 (roadmap)

### ISSUE THREAD

**Issue by zencodex** [uappkit/uapp#6]
- [ ] uapp add 计划增加桌面平台 `electron, tauri`
- [x] `uapp privacy` 生成经常用到的《用户协议》《隐私条款》
- [ ] `uapp sdk` 改变SDK 的更新方式，官方每次下载安装包太麻烦，只有少数模块变化更新
- [ ] 增加插件模块等的管理方式，通过官方 manifest.json 规则管理。保持与在线打包兼容

**Comment by zencodex** [comment]
维护精力有限，暂停其他迭代任务。现有功能继续维护和优化。
